services:
  db:
    image: postgres:15
    container_name: pg_task6
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  web:
    build: ./web
    container_name: flask_task6
    depends_on:
      - db
    env_file: .env
    ports:
      - "5000:5000"
